// Generated by https://quicktype.io

class PopularModel {
  String? backdropPath;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  PopularModel({
    this.backdropPath,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });

  factory PopularModel.fromMap(Map<String, dynamic> map) {
    return PopularModel(
        id: map['id'],
        backdropPath: map['backdropPath'],
        originalLanguage: map['originalLanguage'],
        originalTitle: map['originalTitle'],
        overview: map['overview'],
        popularity: map['popularity'],
        posterPath: map['posterPath'],
        releaseDate: map['releaseDate'],
        title: map['title'],
        video: map['video'],
        voteAverage: (map['voteAverage'] is int)
            ? (map['voteAverage'] as int).toDouble()
            : map['voteAverage'],
        voteCount: map['voteCount']);
  }
}
